services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/e/code/tc_npp_inspector_deployment_testing_web_map/data:/app/blob
    environment:
      - FLASK_ENV=development
